### ISSUE TITLE
Failure in Build

### ISSUE THREAD

**Issue by etiennemunnich** [aws-samples/aws-serverless-webapp-workshop#17]
When attempting to build the project it fails, the log shows the error below:

```
2021-06-16T00:06:17.804Z [INFO]: # Cloning repository: https://git-codecommit.us-east-2.amazonaws.com/v1/repos/wild-rydes
2021-06-16T00:06:18.265Z [INFO]: Cloning into 'wild-rydes'...
2021-06-16T00:06:24.828Z [INFO]: remote:
2021-06-16T00:06:25.971Z [INFO]: remote: Counting objects: 0
2021-06-16T00:06:26.019Z [INFO]: remote: Counting objects: 174
2021-06-16T00:06:26.184Z [INFO]: remote: Counting objects: 174
remote: Counting objects: 174, done.
2021-06-16T00:06:28.169Z [INFO]: Receiving objects:   0% (1/174)
2021-06-16T00:06:28.181Z [INFO]: Receiving objects:   1% (2/174)
2021-06-16T00:06:28.195Z [INFO]: Receiving objects:   2% (4/174)
2021-06-16T00:06:28.232Z [INFO]: Receiving objects:   3% (6/174)

                                                                                
Receiving objects:   4% (7/174)
2021-06-16T00:06:28.238Z [INFO]: Receiving objects:   5% (9/174)
2021-06-16T00:06:28.243Z [INFO]: Receiving objects:   6% (11/174)
2021-06-16T00:06:28.244Z [INFO]: Receiving objects:   7% (13/174)
2021-06-16T00:06:28.254Z [INFO]: Receiving objects:   8% (14/174)
2021-06-16T00:06:28.254Z [INFO]: Receiving objects:   9% (16/174)
2021-06-16T00:06:28.257Z [INFO]: Receiving objects:  10% (18/174)
2021-06-16T00:06:28.257Z [INFO]: Receiving objects:  11% (20/174)

                                                                                
Receiving objects:  12% (21/174)
2021-06-16T00:06:28.259Z [INFO]: Receiving objects:  13% (23/174)
2021-06-16T00:06:28.260Z [INFO]: Receiving objects:  14% (25/174)
2021-06-16T00:06:28.261Z [INFO]: Receiving objects:  15% (27/174)
2021-06-16T00:06:28.261Z [INFO]: Receiving objects:  16% (28/174)
2021-06-16T00:06:28.261Z [INFO]: Receiving objects:  17% (30/174)
2021-06-16T00:06:28.261Z [INFO]: Receiving objects:  18% (32/174)
2021-06-16T00:06:28.267Z [INFO]: Receiving objects:  19% (34/174)
2021-06-16T00:06:28.267Z [INFO]: Receiving objects:  20% (35/174)
2021-06-16T00:06:28.268Z [INFO]: Receiving objects:  21% (37/174)
2021-06-16T00:06:28.268Z [INFO]: Receiving objects:  22% (39/174)
2021-06-16T00:06:28.271Z [INFO]: Receiving objects:  23% (41/174)
2021-06-16T00:06:28.273Z [INFO]: Receiving objects:  24% (42/174)
2021-06-16T00:06:28.273Z [INFO]: Receiving objects:  25% (44/174)
2021-06-16T00:06:28.292Z [INFO]: Receiving objects:  26% (46/174)
2021-06-16T00:06:28.292Z [INFO]: Receiving objects:  27% (47/174)
2021-06-16T00:06:28.297Z [INFO]: Receiving objects:  28% (49/174)
2021-06-16T00:06:28.297Z [INFO]: Receiving objects:  29% (51/174)
2021-06-16T00:06:28.300Z [INFO]: Receiving objects:  30% (53/174)
2021-06-16T00:06:28.306Z [INFO]: Receiving objects:  31% (54/174)
2021-06-16T00:06:28.306Z [INFO]: Receiving objects:  32% (56/174)
2021-06-16T00:06:28.306Z [INFO]: Receiving objects:  33% (58/174)
2021-06-16T00:06:28.308Z [INFO]: Receiving objects:  34% (60/174)
2021-06-16T00:06:28.308Z [INFO]: Receiving objects:  35% (61/174)
2021-06-16T00:06:28.314Z [INFO]: Receiving objects:  36% (63/174)
2021-06-16T00:06:28.320Z [INFO]: Receiving objects:  37% (65/174)

                                                                                
Receiving objects:  38% (67/174)
2021-06-16T00:06:28.320Z [INFO]: Receiving objects:  39% (68/174)
2021-06-16T00:06:28.340Z [INFO]: Receiving objects:  40% (70/174)
2021-06-16T00:06:28.344Z [INFO]: Receiving objects:  41% (72/174)
2021-06-16T00:06:28.345Z [INFO]: Receiving objects:  42% (74/174)

                                                                                
Receiving objects:  43% (75/174)
2021-06-16T00:06:28.354Z [INFO]: Receiving objects:  44% (77/174)
2021-06-16T00:06:28.356Z [INFO]: Receiving objects:  45% (79/174)
2021-06-16T00:06:28.356Z [INFO]: Receiving objects:  46% (81/174)

                                                                                
Receiving objects:  47% (82/174)

                                                                                
Receiving objects:  48% (84/174)
2021-06-16T00:06:28.358Z [INFO]: Receiving objects:  49% (86/174)
2021-06-16T00:06:28.361Z [INFO]: Receiving objects:  50% (87/174)
2021-06-16T00:06:28.367Z [INFO]: Receiving objects:  51% (89/174)
2021-06-16T00:06:28.370Z [INFO]: Receiving objects:  52% (91/174)
2021-06-16T00:06:28.370Z [INFO]: Receiving objects:  53% (93/174)
2021-06-16T00:06:28.375Z [INFO]: Receiving objects:  54% (94/174)
2021-06-16T00:06:28.375Z [INFO]: Receiving objects:  55% (96/174)

                                                                                
Receiving objects:  56% (98/174)

                                                                                
Receiving objects:  57% (100/174)
2021-06-16T00:06:28.377Z [INFO]: Receiving objects:  58% (101/174)
2021-06-16T00:06:28.380Z [INFO]: Receiving objects:  59% (103/174)
2021-06-16T00:06:28.381Z [INFO]: Receiving objects:  60% (105/174)
2021-06-16T00:06:28.382Z [INFO]: Receiving objects:  61% (107/174)
2021-06-16T00:06:28.384Z [INFO]: Receiving objects:  62% (108/174)
2021-06-16T00:06:28.384Z [INFO]: Receiving objects:  63% (110/174)

                                                                                
Receiving objects:  64% (112/174)

                                                                                
Receiving objects:  65% (114/174)
2021-06-16T00:06:28.390Z [INFO]: Receiving objects:  66% (115/174)
2021-06-16T00:06:28.390Z [INFO]: Receiving objects:  67% (117/174)
2021-06-16T00:06:28.390Z [INFO]: Receiving objects:  68% (119/174)
2021-06-16T00:06:28.391Z [INFO]: Receiving objects:  69% (121/174)

                                                                                
Receiving objects:  70% (122/174)
2021-06-16T00:06:28.391Z [INFO]: Receiving objects:  71% (124/174)
2021-06-16T00:06:28.391Z [INFO]: Receiving objects:  72% (126/174)

                                                                                
Receiving objects:  73% (128/174)

                                                                                
Receiving objects:  74% (129/174)

                                                                                
Receiving objects:  75% (131/174)
2021-06-16T00:06:28.392Z [INFO]: Receiving objects:  76% (133/174)
2021-06-16T00:06:28.394Z [INFO]: Receiving objects:  77% (134/174)
2021-06-16T00:06:28.395Z [INFO]: Receiving objects:  78% (136/174)
2021-06-16T00:06:28.395Z [INFO]: Receiving objects:  79% (138/174)

                                                                                
Receiving objects:  80% (140/174)

                                                                                
Receiving objects:  81% (141/174)

                                                                                
Receiving objects:  82% (143/174)

                                                                                
Receiving objects:  83% (145/174)

                                                                                
Receiving objects:  84% (147/174)

                                                                                
Receiving objects:  85% (148/174)

                                                                                
Receiving objects:  86% (150/174)

                                                                                
Receiving objects:  87% (152/174)

                                                                                
Receiving objects:  88% (154/174)

                                                                                
Receiving objects:  89% (155/174)
2021-06-16T00:06:28.396Z [INFO]: Receiving objects:  90% (157/174)

                                                                                
Receiving objects:  91% (159/174)

                                                                                
Receiving objects:  92% (161/174)

                                                                                
Receiving objects:  93% (162/174)

                                                                                
Receiving objects:  94% (164/174)

                                                                                
Receiving objects:  95% (166/174)

                                                                                
Receiving objects:  96% (168/174)

                                                                                
Receiving objects:  97% (169/174)

                                                                                
Receiving objects:  98% (171/174)

                                                                                
Receiving objects:  99% (173/174)
2021-06-16T00:06:28.468Z [INFO]: Receiving objects: 100% (174/174)

                                                                                
Receiving objects: 100% (174/174), 21.64 MiB | 72.17 MiB/s, done.
2021-06-16T00:06:28.469Z [INFO]: Resolving deltas:   0% (0/8)

                                                                                
Resolving deltas:  12% (1/8)

                                                                                
Resolving deltas:  25% (2/8)

                                                                                
Resolving deltas:  37% (3/8)

                                                                                
Resolving deltas:  87% (7/8)

                                                                                
Resolving deltas: 100% (8/8)

                                                                                
Resolving deltas: 100% (8/8), done.
2021-06-16T00:06:28.846Z [INFO]: # Checking for Git submodules at: /codebuild/output/src664534611/src/wild-rydes/.gitmodules
2021-06-16T00:06:28.870Z [INFO]: # Retrieving cache...
2021-06-16T00:06:28.909Z [INFO]: # Extracting cache...
2021-06-16T00:06:28.917Z [INFO]: # Extraction completed
2021-06-16T00:06:28.918Z [INFO]: # Retrieving environment cache...
2021-06-16T00:06:28.938Z [INFO]: # Retrieved environment cache
2021-06-16T00:06:28.939Z [INFO]: # Ensuring NPM package '@aws-amplify/cli' is version: 'latest'
2021-06-16T00:06:35.298Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 4.29.4 to 5.0.0...
2021-06-16T00:07:29.745Z [INFO]: # Done patching NPM package '@aws-amplify/cli'
2021-06-16T00:07:35.801Z [INFO]: ## Starting Backend Build
                                 # Starting phase: build
2021-06-16T00:07:45.784Z [INFO]: [0mAmplify AppID found: d30lcoh54e6r9b. Amplify App name is: wild-rydes[0m
2021-06-16T00:07:45.891Z [INFO]: [0mBackend environment prod found in Amplify Console app: wild-rydes[0m
2021-06-16T00:07:46.703Z [WARNING]: - Fetching updates to backend environment: prod from the cloud.
2021-06-16T00:07:46.889Z [WARNING]: ✔ Successfully pulled backend environment prod from the cloud.
2021-06-16T00:07:46.893Z [INFO]: 
2021-06-16T00:07:49.894Z [INFO]: [33mNote: It is recommended to run this command from the root of your app directory[39m
2021-06-16T00:07:55.451Z [WARNING]: - Initializing your environment: prod
2021-06-16T00:07:55.713Z [WARNING]: ✔ Initialized provider successfully.
2021-06-16T00:07:56.014Z [WARNING]: - Updating resources in the cloud. This may take a few minutes...
2021-06-16T00:07:56.689Z [WARNING]: Error updating cloudformation stack
2021-06-16T00:07:56.691Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2021-06-16T00:07:56.692Z [WARNING]: ✖ There was an error initializing your environment.
2021-06-16T00:07:56.696Z [INFO]: [0mError [ValidationError]: No updates are to be performed.[0m
                                 [0m    at Request.extractError (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/query.js:50:29)[0m
                                 [0m    at Request.callListeners (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)[0m
                                 [0m    at Request.emit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)[0m
                                 [0m    at Request.emit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:14)[0m
                                 [0m    at Request.transition (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)[0m
                                 [0m    at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)[0m
                                 [0m    at /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10[0m
                                 [0m    at Request.<anonymous> (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)[0m
                                 [0m    at Request.<anonymous> (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:690:12)[0m
                                 [0m    at Request.callListeners (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)[0m
                                 [0m    at Request.emit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)[0m
                                 [0m    at Request.emit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:14)[0m
                                 [0m    at Request.transition (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)[0m
                                 [0m    at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)[0m
                                 [0m    at /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10[0m
                                 [0m    at Request.<anonymous> (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)[0m
                                 [0m    at Request.<anonymous> (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:690:12)[0m
                                 [0m    at Request.callListeners (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)[0m
                                 [0m    at callNextListener (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:96:12)[0m
                                 [0m    at IncomingMessage.onEnd (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:313:13)[0m
                                 [0m    at IncomingMessage.emit (events.js:326:22)[0m
                                 [0m    at IncomingMessage.EventEmitter.emit (domain.js:483:12)[0m
                                 [0m    at endReadableNT (_stream_readable.js:1241:12)[0m
                                 [0m    at processTicksAndRejections (internal/process/task_queues.js:84:21) {[0m
                                 [0m  code: 'ValidationError',[0m
                                 [0m  time: 2021-06-16T00:07:56.689Z,[0m
                                 [0m  requestId: '2766a9b6-04dc-4e10-bb78-ec8887349c2f',[0m
                                 [0m  statusCode: 400,[0m
                                 [0m  retryable: false,[0m
                                 [0m  retryDelay: 18.478256571125627[0m
                                 [0m}[0m
2021-06-16T00:07:56.717Z [ERROR]: !!! Build failed
2021-06-16T00:07:56.717Z [ERROR]: !!! Non-Zero Exit Code detected
2021-06-16T00:07:56.717Z [INFO]: # Starting environment caching...
2021-06-16T00:07:56.718Z [INFO]: # Environment caching completed
Terminating logging...
```

**Comment by blghns** [comment]
This can be fixed with changing Amplify CLI version from Latest to 4.29.4 in the Build Settings 
![image](https://user-images.githubusercontent.com/5798789/122244052-9416c780-ce92-11eb-85a9-1be36a009d5b.png)

**Comment by renebrandel** [comment]
Hi @etiennemunnich - we've fixed this issue with CLI version 5.0.1. Sorry for the unfortunate experience. https://github.com/aws-amplify/amplify-cli/pull/7548
