### ISSUE TITLE
Frontend Build Error in Amplify

### ISSUE THREAD

**Issue by danflood94** [aws-samples/aws-serverless-webapp-workshop#7]
Module build failed (from ./node_modules/thread-loader/dist/cjs.js): 

`020-11-03T17:43:20.483Z [INFO]: ERROR  Failed to compile with 1 errors5:43:20 PM
2020-11-03T17:43:20.485Z [INFO]: Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
                                 Thread Loader (Worker 0)
                                 No ESLint configuration found.
                                 at PoolWorker.fromErrorObj (/codebuild/output/src472483307/src/AmplifyTest/node_modules/thread-loader/dist/WorkerPool.js:262:12)
                                 at Config.getLocalConfigHierarchy (/codebuild/output/src472483307/src/AmplifyTest/node_modules/eslint/lib/config.js:268:39)
                                 at Config.getConfigHierarchy (/codebuild/output/src472483307/src/AmplifyTest/node_modules/eslint/lib/config.js:192:43)
                                 at Config.getConfigVector (/codebuild/output/src472483307/src/AmplifyTest/node_modules/eslint/lib/config.js:299:21)
                                 at Config.getConfig (/codebuild/output/src472483307/src/AmplifyTest/node_modules/eslint/lib/config.js:342:29)
                                 at processText (/codebuild/output/src472483307/src/AmplifyTest/node_modules/eslint/lib/cli-engine.js:181:33)
                                 at CLIEngine.executeOnText (/codebuild/output/src472483307/src/AmplifyTest/node_modules/eslint/lib/cli-engine.js:690:40)
                                 at lint (/codebuild/output/src472483307/src/AmplifyTest/node_modules/eslint-loader/index.js:278:17)
                                 at transform (/codebuild/output/src472483307/src/AmplifyTest/node_modules/eslint-loader/index.js:252:18)
                                 at /codebuild/output/src472483307/src/AmplifyTest/node_modules/loader-fs-cache/index.js:127:18
                                 at ReadFileContext.callback (/codebuild/output/src472483307/src/AmplifyTest/node_modules/loader-fs-cache/index.js:31:14)
                                 You may use special comments to disable some warnings.
                                 Use // eslint-disable-next-line to ignore the next line.
                                 Use /* eslint-disable */ to ignore all warnings in a file.
2020-11-03T17:43:20.486Z [WARNING]: ERROR  Build failed with errors.`

When attempting to build in AWS Amplify, following the workshop. This is from the initial deploy in the repository page of the workshop.

**Comment by rts-rob** [comment]
I cannot reproduce this issue using Cloud 9 with either Amazon Linux or Amazon Linux 2. Are you still experiencing it?
